#!/bin/bash
# Program akan memulai proses...
# Copyright (C) 2022 
#
# This file is a part of < https://github.com/mrismanaziz/PyroMan-Userbot/ >
# PLease read the GNU Affero General Public License in
# <https://www.github.com/mrismanaziz/PyroMan-Userbot/blob/main/LICENSE/>.
#
# 

python3 -m ProjectMan
